export const CLINICAL_DEPARTMENTS = [
  'General Medicine',
  'Cardiology',
  'Neurology',
  'Orthopedics',
  'Pediatrics',
  'Gynecology & Obstetrics',
  'Surgery / General Surgery',
  'Dermatology',
  'ENT',
  'Ophthalmology',
  'Psychiatry',
  'Urology',
  'Nephrology',
  'Gastroenterology',
  'Pulmonology',
  'Endocrinology',
  'Oncology',
  'Radiology',
  'Pathology',
  'Anesthesiology',
  'Critical Care / ICU',
  'Physiotherapy & Rehabilitation',
  'Dental / Dentistry',
  'Nutrition & Dietetics',
  'Emergency',
] as const;

export const SUPPORT_DEPARTMENTS = [
  'General',
  'Pharmacy',
  'Laboratory',
  'Nursing',
  'Front Desk',
  'Billing / Accounts',
  'Administration',
  'Management',
] as const;

export const ALL_HOSPITAL_DEPARTMENTS = [
  'General',
  'General Medicine',
  'Cardiology',
  'Neurology',
  'Orthopedics',
  'Pediatrics',
  'Gynecology & Obstetrics',
  'Surgery / General Surgery',
  'Dermatology',
  'ENT',
  'Ophthalmology',
  'Psychiatry',
  'Urology',
  'Nephrology',
  'Gastroenterology',
  'Pulmonology',
  'Endocrinology',
  'Oncology',
  'Radiology',
  'Pathology',
  'Anesthesiology',
  'Critical Care / ICU',
  'Physiotherapy & Rehabilitation',
  'Dental / Dentistry',
  'Nutrition & Dietetics',
  'Emergency',
  'Pharmacy',
  'Laboratory',
  'Nursing',
  'Front Desk',
  'Billing / Accounts',
  'Administration',
  'Management',
] as const;

export type ClinicalDepartment = (typeof CLINICAL_DEPARTMENTS)[number];
export type HospitalDepartment = (typeof ALL_HOSPITAL_DEPARTMENTS)[number];
